
services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/main/static
    ports:
      - 8000:8000
    env_file: .env

  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/main/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static:
