services:
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}:${GITHUB_PREVIOUS_SHA}"
    image: "${NGINX_IMAGE}:${GITHUB_PREVIOUS_SHA}"
    ports:
      - 80:80
    volumes:
      - static:/main/static

    networks:
      - application_connect

networks:
  application_connect:
    external: true


volumes:
  static: