services:
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/main/static
    depends_on:
      - web

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn Application_Main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/main/static
    expose:
      - 8000
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: "celery -A Application_Main worker"
    depends_on:
      - web
      - redis
      - db
    restart: on-failure

volumes:
  db-data:
  static:
  redisdata:

secrets:
  db-password:
    file: db/password.txt