
services:
  web:
    image: "${WEB_IMAGE}:${GITHUB_SHA}"
    command: gunicorn "Application_Main".wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/usr/src/app/static
      - base:/usr/src/app
      - type: bind
        source: $HOST/etc/letsencrypt/live/findmyitem.app/
        target: /usr/share/ssl_certs/
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - application_connect

  nginx:
    image: "${NGINX_IMAGE}:${GITHUB_SHA}"
    restart: unless-stopped
    command:
      - mkdir /usr/share/ssl_certs/ && chmod 755 /usr/share/ssl_certs
      - ls -l /usr/share/ssl_certs
    volumes:
      - static:/usr/src/app/static
      - type: bind
        source: $HOST/etc/letsencrypt/live/findmyitem.app/fullchain.pem
        target: /usr/share/ssl_certs/fullchain.pem
      - type: bind
        source: $HOST/etc/letsencrypt/live/findmyitem.app/privkey.pem
        target: /usr/share/ssl_certs/privkey.pem

    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - application_connect

networks:
  application_connect:
    external: true

volumes:
  static:
  base:
