
services:
  web:
    image: "${WEB_IMAGE}:${GITHUB_SHA}"
    command: gunicorn Application_Main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/usr/src/app/static
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - application_connect

  nginx:
    image: "${NGINX_IMAGE}:${GITHUB_SHA}"
    volumes:
      - static:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - application_connect

networks:
  application_connect:
    external: true

volumes:
  static:
