
services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/main/static
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - application_connect

  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static:/main/static
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - application_connect

networks:
  application_connect:
    external: true

volumes:
  static:
