services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-web.ci
    command: gunicorn Application_Main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/main/static
    expose:
      - 8000
    depends_on:
      - redis

volumes:
  static:

secrets:
  db-password:
    file: db/password.txt