# Generated by Django 4.2.4 on 2023-09-08 05:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticketID", models.AutoField(primary_key=True, serialize=False)),
                ("ticketType", models.CharField(max_length=100)),
                ("created_dateTime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("itemID", models.AutoField(primary_key=True, serialize=False)),
                ("itemName", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                ("imageURL", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "found_dateTime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "ticketID",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="items",
                        to="base_functions.ticket",
                        verbose_name="ticketID",
                    ),
                ),
            ],
        ),
    ]
