# Generated by Django 4.2.4 on 2023-09-22 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAdditionalProfile',
            fields=[
                ('userProfileNumber', models.AutoField(primary_key=True, serialize=False)),
                ('userTelegramID', models.CharField(max_length=100)),
                ('userProfilePicture', models.ImageField(blank=True, null=True, upload_to='profile-images/')),
                ('usedID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
