# Generated by Django 4.2.4 on 2023-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalprofile',
            name='userVerifiedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
