# Generated by Django 4.2.4 on 2023-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_functions', '0002_useradditionalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalprofile',
            name='userPhoneNumber',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='useradditionalprofile',
            name='userTelegramID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
